from PyQt5 import QtCore, QtGui, QtWidgets


class HebbWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("HebbWindow")
        self.resize(430, 150)
        self.setMinimumSize(QtCore.QSize(430, 150))
        self.setMaximumSize(QtCore.QSize(430, 150))
        self.centralWidget = QtWidgets.QWidget(self)
        self.centralWidget.setObjectName("centralWidget")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(210, 10, 16, 131))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(240, 90, 19, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(240, 120, 19, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_input1 = QtWidgets.QLineEdit(self.centralWidget)
        self.line_input1.setGeometry(QtCore.QRect(270, 94, 41, 20))
        self.line_input1.setStyleSheet("background: red")
        self.line_input1.setAlignment(QtCore.Qt.AlignCenter)
        self.line_input1.setReadOnly(True)
        self.line_input1.setObjectName("line_input1")
        self.line_input2 = QtWidgets.QLineEdit(self.centralWidget)
        self.line_input2.setGeometry(QtCore.QRect(270, 120, 41, 20))
        self.line_input2.setStyleSheet("background: red")
        self.line_input2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_input2.setReadOnly(True)
        self.line_input2.setObjectName("line_input2")
        self.btn_toggle_input1 = QtWidgets.QPushButton(self.centralWidget)
        self.btn_toggle_input1.setGeometry(QtCore.QRect(320, 94, 20, 20))
        self.btn_toggle_input1.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_toggle_input1.setAutoDefault(False)
        self.btn_toggle_input1.setDefault(False)
        self.btn_toggle_input1.setFlat(False)
        self.btn_toggle_input1.setObjectName("btn_toggle_input1")
        self.btn_toggle_input2 = QtWidgets.QPushButton(self.centralWidget)
        self.btn_toggle_input2.setGeometry(QtCore.QRect(320, 120, 20, 20))
        self.btn_toggle_input2.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_toggle_input2.setObjectName("btn_toggle_input2")
        self.line_output = QtWidgets.QLineEdit(self.centralWidget)
        self.line_output.setGeometry(QtCore.QRect(350, 110, 41, 20))
        self.line_output.setStyleSheet("background: red")
        self.line_output.setAlignment(QtCore.Qt.AlignCenter)
        self.line_output.setReadOnly(True)
        self.line_output.setObjectName("line_output")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(400, 105, 19, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(110, 10, 16, 131))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_weight1 = QtWidgets.QLineEdit(self.centralWidget)
        self.line_weight1.setGeometry(QtCore.QRect(240, 40, 51, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_weight1.sizePolicy().hasHeightForWidth())
        self.line_weight1.setSizePolicy(sizePolicy)
        self.line_weight1.setAlignment(QtCore.Qt.AlignCenter)
        self.line_weight1.setReadOnly(True)
        self.line_weight1.setObjectName("line_weight1")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(250, 11, 24, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(21, 10, 19, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(11, 68, 41, 20))
        self.lineEdit_7.setStyleSheet("background: red")
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(11, 94, 41, 20))
        self.lineEdit_8.setStyleSheet("background: green")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(11, 42, 41, 20))
        self.lineEdit_9.setStyleSheet("background: red")
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(11, 120, 41, 20))
        self.lineEdit.setStyleSheet("background: green")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(62, 120, 41, 20))
        self.lineEdit_2.setStyleSheet("background: green")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(62, 68, 41, 20))
        self.lineEdit_11.setStyleSheet("background: green")
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(62, 94, 41, 20))
        self.lineEdit_10.setStyleSheet("background: red")
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(62, 42, 41, 20))
        self.lineEdit_12.setStyleSheet("background: red")
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(70, 10, 19, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(150, 10, 16, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_target2 = QtWidgets.QLineEdit(self.centralWidget)
        self.line_target2.setGeometry(QtCore.QRect(133, 68, 41, 20))
        self.line_target2.setStyleSheet("background: red")
        self.line_target2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_target2.setReadOnly(True)
        self.line_target2.setObjectName("line_target2")
        self.line_target1 = QtWidgets.QLineEdit(self.centralWidget)
        self.line_target1.setGeometry(QtCore.QRect(133, 42, 41, 20))
        self.line_target1.setStyleSheet("background: red")
        self.line_target1.setAlignment(QtCore.Qt.AlignCenter)
        self.line_target1.setReadOnly(True)
        self.line_target1.setObjectName("line_target1")
        self.line_target4 = QtWidgets.QLineEdit(self.centralWidget)
        self.line_target4.setGeometry(QtCore.QRect(133, 120, 41, 20))
        self.line_target4.setStyleSheet("background: red")
        self.line_target4.setAlignment(QtCore.Qt.AlignCenter)
        self.line_target4.setReadOnly(True)
        self.line_target4.setObjectName("line_target4")
        self.line_target3 = QtWidgets.QLineEdit(self.centralWidget)
        self.line_target3.setGeometry(QtCore.QRect(133, 94, 41, 20))
        self.line_target3.setStyleSheet("background: red")
        self.line_target3.setAlignment(QtCore.Qt.AlignCenter)
        self.line_target3.setReadOnly(True)
        self.line_target3.setObjectName("line_target3")
        self.btn_toggle_target1 = QtWidgets.QPushButton(self.centralWidget)
        self.btn_toggle_target1.setGeometry(QtCore.QRect(180, 42, 20, 20))
        self.btn_toggle_target1.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_toggle_target1.setAutoDefault(False)
        self.btn_toggle_target1.setDefault(False)
        self.btn_toggle_target1.setFlat(False)
        self.btn_toggle_target1.setObjectName("btn_toggle_target1")
        self.btn_toggle_target2 = QtWidgets.QPushButton(self.centralWidget)
        self.btn_toggle_target2.setGeometry(QtCore.QRect(180, 68, 20, 20))
        self.btn_toggle_target2.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_toggle_target2.setObjectName("btn_toggle_target2")
        self.btn_toggle_target4 = QtWidgets.QPushButton(self.centralWidget)
        self.btn_toggle_target4.setGeometry(QtCore.QRect(180, 120, 20, 20))
        self.btn_toggle_target4.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_toggle_target4.setObjectName("btn_toggle_target4")
        self.btn_toggle_target3 = QtWidgets.QPushButton(self.centralWidget)
        self.btn_toggle_target3.setGeometry(QtCore.QRect(180, 94, 20, 20))
        self.btn_toggle_target3.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_toggle_target3.setObjectName("btn_toggle_target3")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(310, 11, 24, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line_weight2 = QtWidgets.QLineEdit(self.centralWidget)
        self.line_weight2.setGeometry(QtCore.QRect(300, 40, 51, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_weight2.sizePolicy().hasHeightForWidth())
        self.line_weight2.setSizePolicy(sizePolicy)
        self.line_weight2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_weight2.setReadOnly(True)
        self.line_weight2.setObjectName("line_weight2")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(380, 11, 16, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.line_bias = QtWidgets.QLineEdit(self.centralWidget)
        self.line_bias.setGeometry(QtCore.QRect(360, 40, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_bias.sizePolicy().hasHeightForWidth())
        self.line_bias.setSizePolicy(sizePolicy)
        self.line_bias.setAlignment(QtCore.Qt.AlignCenter)
        self.line_bias.setReadOnly(True)
        self.line_bias.setObjectName("line_bias")
        self.setCentralWidget(self.centralWidget)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("HebbWindow", "Regra de Hebb"))
        self.label_8.setText(_translate("HebbWindow", "x1"))
        self.label_9.setText(_translate("HebbWindow", "x2"))
        self.line_input1.setText(_translate("HebbWindow", "-1"))
        self.line_input2.setText(_translate("HebbWindow", "-1"))
        self.btn_toggle_input1.setText(_translate("HebbWindow", "+"))
        self.btn_toggle_input2.setText(_translate("HebbWindow", "+"))
        self.line_output.setText(_translate("HebbWindow", "-1"))
        self.label_10.setText(_translate("HebbWindow", "y"))
        self.line_weight1.setText(_translate("HebbWindow", "0"))
        self.label_5.setText(_translate("HebbWindow", "w1"))
        self.label_2.setText(_translate("HebbWindow", "x1"))
        self.lineEdit_7.setText(_translate("HebbWindow", "-1"))
        self.lineEdit_8.setText(_translate("HebbWindow", "1"))
        self.lineEdit_9.setText(_translate("HebbWindow", "-1"))
        self.lineEdit.setText(_translate("HebbWindow", "1"))
        self.lineEdit_2.setText(_translate("HebbWindow", "1"))
        self.lineEdit_11.setText(_translate("HebbWindow", "1"))
        self.lineEdit_10.setText(_translate("HebbWindow", "-1"))
        self.lineEdit_12.setText(_translate("HebbWindow", "-1"))
        self.label_4.setText(_translate("HebbWindow", "x2"))
        self.label_3.setText(_translate("HebbWindow", "t"))
        self.line_target2.setText(_translate("HebbWindow", "-1"))
        self.line_target1.setText(_translate("HebbWindow", "-1"))
        self.line_target4.setText(_translate("HebbWindow", "-1"))
        self.line_target3.setText(_translate("HebbWindow", "-1"))
        self.btn_toggle_target1.setText(_translate("HebbWindow", "+"))
        self.btn_toggle_target2.setText(_translate("HebbWindow", "+"))
        self.btn_toggle_target4.setText(_translate("HebbWindow", "+"))
        self.btn_toggle_target3.setText(_translate("HebbWindow", "+"))
        self.label_6.setText(_translate("HebbWindow", "w2"))
        self.line_weight2.setText(_translate("HebbWindow", "0"))
        self.label_7.setText(_translate("HebbWindow", "b"))
        self.line_bias.setText(_translate("HebbWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = HebbWindow()
    ui.show()
    sys.exit(app.exec_())

